### ISSUE TITLE
crypto_kdf_derive_from_key breaks for subkey_id > 2^31−1

### ISSUE THREAD

**Issue by webmaster128** [jedisct1/libsodium.js#135]
`crypto_kdf_derive_from_key` converts a JavaScript number into uint64_t for parameter `subkey_id`.

Unfortunately, this only works up to  2^31−1 = 2147483647 = 0x7FFFFFFF. As soon as the signed int32 maximum is exceeded, the error "subkey_id must be an unsigned integer" is raised.

I was expecting to have Number.MAX_SAFE_INTEGER as a limit, which is the max positive integer that  IEEE 754 can represent. Even then, it may be a problem for app developers to have a lower input range that documented for C libsodium.

If it is not possible to increase the input range, I think the error message should be more helpful, e.g. "The JavaScript wrapper of libsodium limits subkey_id to  2^31−1." because 0x80000000 is still unsigned.

**Comment by jedisct1** [comment]
Pretty sure nothing at all in this wrapper accepts integers larger than 2^31-1.

**Comment by webmaster128** [comment]
This particular problem occurs because [bitwise operations are performed after converting to signed 32bit integers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators) in JavaScript, which leads to `(subkey_id | 0) == -2147483648` for `subkey_id = 0x80000000 = 2147483648`. So this check could be changed.

But I have no idea to what extend `number`s can be passed to the emscripten-generated code.

**Comment by jedisct1** [comment]
In the emscripten interface, 64-bit values are passed as two 32 bits-values.

**Comment by paragonie-scott** [comment]
#218 should fix this.

**Comment by jedisct1** [comment]
#218 seems to just add one bit.

We still can't go up to `Number.MAX_SAFE_INTEGER`. Everything is truncated to 32 bit.

```text
> 9007199254740991 >>> 1
2147483647
```

**Comment by paragonie-scott** [comment]
Oh lovely.

**Comment by paragonie-scott** [comment]
It seems like the best we can do is divide by `1 << 30`, then shift right twice.

```
let x = ((Number.MAX_SAFE_INTEGER / 1073741824) | 0) >>> 2;
let y = (1 << 21) - 1;
console.log([x, y]);
// [ 2097151, 2097151 ]
```

**Comment by jedisct1** [comment]
Looks like the way to go.
